### ISSUE TITLE
Add lib to format dates

### ISSUE THREAD

**Issue by aandrey1993** [Arboker/admin_ui#11]
Добрый вечер. Меня зовут Андрей. Я делаю ревью Вашего тестового задания. По возникшим вопросам буду открывать тикеты. Вы можете оставить ответ в комментарии или внести соответствующие правки в код.

## Описание
В проекте, все даты форматируется вручную, из-за чего приходится под каждый формат даты писать отдельный парсинг:

![изображение](https://user-images.githubusercontent.com/49781313/144722900-db8ecc59-2328-42c1-8468-3ff94ce334e9.png)

![изображение](https://user-images.githubusercontent.com/49781313/144722906-ed5ce0c8-abcd-4ff8-8cf5-b93fa2aa11d4.png)

Есть готовые библиотеки для работы с датами, которые очень  упрощают разработку. 

## Задача
Попробуйте посмотреть в сторону `moment js` и переписать функции форматирования дат c её помощью

**Comment by Arboker** [comment]
#14
