### ISSUE TITLE
Function using recursion

### ISSUE THREAD

**Issue by aandrey1993** [Arboker/admin_ui#12]
## Описание
В файле main.js у Вас есть функция `randomNumSum` в которой используется рекурсия

![изображение](https://user-images.githubusercontent.com/49781313/144723025-a931a065-f27b-44b9-9221-3e78ad8671ca.png)

## Задача
1. Распишите, пожалуйста, для чего нужна данная функция и какая в ней заложена логика ? 
2. По какой причине делается `reverse()` при возвращении результата из функции, потом ещё после его вызова ? 

![изображение](https://user-images.githubusercontent.com/49781313/144723105-9ea64d7d-08d5-4008-827a-1f5f5596fbfe.png)

![изображение](https://user-images.githubusercontent.com/49781313/144723113-330ce457-17ef-434b-b6d6-af5bba56c26e.png)

3. Можете уменьшить количество вложенных условий в данной функции без изменения результата её работы ?

**Comment by Arboker** [comment]
1. Данная функция нужно для генерирования сумм из чисел (в моем случаи из рандомного числа users). 
То есть я создаю массив, где есть параметр users, допустим - 21. И у меня есть 10 страничек и мне нужно заполнить цифрами  эти 10 страничек и в сумме они должны получить 21. Это все должно быть в рандомном порядке.
2.  Подправил
3. Нет, не смогу.

#16

**Comment by Arboker** [comment]
1. Мне нужно сделать поддельный запрос для возвращения данных для chart. 
Этот объект должен содержать в себе: дату (date), количество юзеров (users), количество уникальных юзеров (unic_users) и 10 страничек, которые в себе должны содержать название и количество юзеров.

Сумма юзеров из 10 страничек должны в итоге получить число из объекта users. Число users сгенерировано рандомно. То есть может быть любое число. Каждая страничка из массива pages должна иметь рандомно сгенерированное число, для этого используется рекурсия:
1) Мы генерируем рандомное число, дальше мы округляем операцию (сумма чисел переданная (users) минус рандомно сгенерированное число). Если это число получилось меньше нуля, мы присваиваем ему значение 0 (чтобы не было число отрицательное). 
2) Это число мы заносим в наш массив, дольше мы смотрим, если мы передели в аргументе второе число (то есть количество страниц) больше 1, то мы запускаем рекурсию, и передаем данные, где сумма = прошлая сумма минус сгенерированное число, второе значение = количество прошлых страниц минус 1 и сам массив.
3) Дальше вы возвращаем массив из этой функции, так как у нас массив из рандомно сгенерированных чисел, но не равняется из суммы чисел, которые мы передали, мы должны пройтись по нему и сделать reduce, где мы проверяем, если index из map функции не соответствует индексу, который проходит итерацию в reduce, и суммирую его с прошлыми числами.

Надеюсь понятно объяснил :)

2. Ну тут я подправил
3. Немного недопонял, что нужно сделать? Просто эту функцию я не знаю, как сократить.

**Comment by maximburdiean** [comment]
> 4\. Немного недопонял, что нужно сделать? Просто эту функцию я не знаю, как сократить.

@aandrey1993 , сможете пояснить?

**Comment by aandrey1993** [comment]
@Arboker если сохранить ту логику которая сейчас есть, можно использовать ранний return из рекурсии при выполнении условии и от всего дерева if и else можно уйти. Код сразу становится более читабельный. Для сравнение `cap` с 0 можно использовать тернарную операцию. 
В итого получаем следующее:

![изображение](https://user-images.githubusercontent.com/49781313/145083982-8a0b14bc-4744-43bd-87ae-4a078392fa69.png)

![изображение](https://user-images.githubusercontent.com/49781313/145084073-733562e3-8667-4afc-8848-cf556d2aea38.png)

**Comment by Arboker** [comment]
Да, сейчас я понял, спасибо.  Подумал о переделывании самой логике.
