### ISSUE TITLE
Unnecessary transformations over an array

### ISSUE THREAD

**Issue by aandrey1993** [Arboker/admin_ui#13]
## Описание
В компоненте `SupportTable`, перед выводом данных в таблице, выполняется дополнительный обход и изменения массива для форматирования даты

![изображение](https://user-images.githubusercontent.com/49781313/144723218-2f7b4da1-e1a2-4b09-91d1-acc5565a20b8.png)

## Задача
Почему бы сразу в рендер функции, не вызвать функцию для форматирования дат ? Тем самым получится уйти от лишнего обхода массива. Для больших объемах данных это будет хорошей оптимизацией

![изображение](https://user-images.githubusercontent.com/49781313/144723273-01ce917d-726a-417b-b478-fedbb58633e5.png)

**Comment by Arboker** [comment]
#17
