### ISSUE TITLE
Support page questions

### ISSUE THREAD

**Issue by aandrey1993** [Arboker/admin_ui#15]
## Описание

На странице `Support`, если при выполнении поиска не найдены результаты, отображается пустая таблица, но в `Rezultate cautare:` все равно отображается имя.

![изображение](https://user-images.githubusercontent.com/49781313/144723475-a0d00381-3c30-443f-84c9-81bf946b6228.png)

## Задача
Сможете сделать чтобы если данные не найдены, таблица не отображалась, а в разделе `Rezultate cautare:` был текст: `Nu s-a găsit nimic pentru criteriile de filtrare selectate` ?

**Comment by Arboker** [comment]
#18
